BloomBooks/BloomLibrary2

src/components/SearchBox.tsx
src/components/header/Header.tsx
src/stories/index.tsx

* Use material-ui icon
* add html tooltip
* add placeholder text
* add cancel button when search text exists
* add to storybook
* some refactoring in SearchBox imports
* got search to not lose focus
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/18)

BL-8119 Start on refining search box

---

src/model/Book.ts

When it's not observable and we try to edit it with a controlled field, editing doesn't work.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/28)

Make librarianNote observable

---

package.json
src/components/BookDetail/BookExtraPanels.tsx
yarn.lock

Note that this uses code splitting so that it is only downloaded if the user is a moderator. At the price of some delay, we could probably further delay getting it to when someone actually expands the JSON panel, but it doesn't feel worth it; you only pay this price once then it will be cached.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/30)

Show Formatted JSON in the Staff Raw Books Data

---

public/index.html

Without these attributes, particularly the crossorigin one, the resources preload and then load again when needed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/36)

Fix preload links so they actually work.

---

src/components/Admin/BookshelfChooser.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/63)

Fix BookshelfChooser to set key instead of englishName

---

src/Router.ts
src/components/ByLanguageGroups.tsx
src/components/SearchBox.tsx

Trade-off: This does make it impossible to do compound searches using covid-19 for now, like you could not search for "covid-19 language:foo".
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/73)

Redirect Urls mentioning covid19, and searches for covid19 terms

---

src/model/ArtifactVisibilitySettings.ts

The id field gets serialized to JSON and pollutes the value in our database, which is a minor nuisance.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/122)

Deleted unused member variable

---

src/components/Breadcrumbs.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/124)

Fixes a bug that prevented loading plain book/id URLs

---

src/export/freeLearningIO.ts

Means adding a version. Since our License page refers people to version 4.0 of CC, I think it's fair to assume that's the version they are providing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/143)

Make license IDs for Free Learning CSV conform to SPDX

---

src/components/BookDetail/ArtifactGroup.tsx
src/model/ArtifactVisibilitySettings.ts

Conditional creation of settings objects could break the rules with bad results
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/147)

Fix a bug in DetailView's use of hooks

---

src/components/ReadBookPage.tsx

This change will keep bloom-player from interfering with Bloom Library sending analytics when the change is made for bloom-player to send its own analytics.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/156)

Fix bloom-player iframe url for upcoming changes (BL-8874)

---

src/components/SearchBox.tsx

* we were getting an error from React about
"Cannot update during an existing state transition..."
* moved "extra" stuff inside of handleSearch() and
was able to eliminate 'enteredSearch' state
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/158)

Fix Search box

---

src/components/Grid/GridControlInternal.tsx

* encoded colon messed up grid search by topic
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/159)

BL-8902 Get grid search box to work

---

src/components/BulkEdit/BulkEditPage.tsx
src/components/Grid/GridControlInternal.tsx
src/components/Routes.tsx

* the change to GridControlInternal is just to avoid shadowing a variable
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/160)

BL-8904 Use search box in bulk edit page

---

src/components/Admin/StaffMultiChoosers.tsx
src/components/BulkEdit/BulkChangeFunctions.ts
src/connection/ParseServerConnection.ts

Old versions of Bloom before 3.8 (notably, REACH) did not prefix topic
tags.  If users add a plain tag string, we don't want to assume that a
topic tag is wanted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/176)

Force a default tag prefix "tag:" is user doesn't give one (BL-8990)

---

src/components/Grid/GridControlInternal.tsx
src/components/SearchBox.tsx

For instance, "collectionName:my-books", "collectionName:covid19",
or "collectionName:pratham-derivatives" would all translate into the
filters used by those collections.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/178)

Allow searching/filtering by collectionName:urlkey (BL-8880)

---

src/components/Footer.tsx
src/components/header/Header.tsx
src/index.css

* Header and Footer had minimum widths that caused
horizontal scrolling
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/200)

BL-9224 Narrow screen width problems

---

src/components/BlorgLink.tsx
src/components/CheapCard.tsx
src/components/Routes.tsx
src/components/RowOfCards.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

Use the React-Router link if the target is internal, otherwise use a `<a>` that opens a new tab.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/206)

Allow contentful links to open external links

---

src/components/ByLanguageGroups.tsx
src/components/LanguageCard.tsx
src/components/LanguageFeatureList.tsx
src/components/LanguageGroup.tsx
src/components/LanguageLink.tsx
src/components/statistics/BookStatsReport.tsx
src/model/Collections.tsx
src/model/Language.ts

* Special handling of Chinese Simplified
* if the UI language is the language in question, make the autonym primary instead of English
* add bcp47 codes to the secondary name if the other names aren't already made of that code (we have a few examples of this)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/212)

Some tweaks around how we decide which form of a language name to show

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/232)

Remove "books" and "book" (and es/fr translations) from searches (BL-9291)

---

src/analytics/CollectionAnalyticsInfo.ts
src/components/ByLevelGroups.tsx
src/components/ByTopicsGroups.tsx
src/components/CheapCard.tsx
src/components/Routes.tsx
src/components/StoryCard.tsx

* added initial slash to de-relativize CheapCard url
* factor out code to get iso from 'language:code' safely
* also fixed duplicate of "page/create/" in StoryCard
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/246)

BL-9308 More card duplicates url parts

---

src/components/BookCard.tsx
src/components/LanguageFeatureList.tsx

* caused by CSS reset, apparently
* slight increase to CheapCard height
* change to language feature list max-height calculation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/252)

BL-9374 Fix book card layout

---

src/components/BookCard.tsx
src/components/BookCardGroup.tsx
src/components/BookGroup.tsx
src/components/CardGroup.tsx
src/components/CardSwiper.tsx
src/components/CheapCard.tsx
src/components/CollectionCard.tsx
src/components/FeatureMatrix.tsx
src/components/LanguageCard.tsx
src/components/LanguageGroup.tsx
src/components/RowOfCards.tsx
src/components/SingleRowCardSwiper.tsx
src/components/StoryCard.tsx
src/components/banners/Banner.tsx
src/components/banners/Blurb.tsx
src/connection/GetQueryResultsUI.tsx
src/model/RouterContent.tsx
src/responsiveUtilities.ts
src/theme.tsx

https://issues.bloomlibrary.org/youtrack/issue/BL-9317
Move cards to the new left-aligned, space-saving design
Banner sizing
Card sizing
Cards spacing
Clarified the names around the 2 versions of cardswiper
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/260)

BL-9317 Adjust to phone screens (wip)

---

src/components/Routes.tsx

Makes routes like /_preview/page/id work just like /page/id, except preview data is used instead of published. Contentful is configured to generate such paths if the user requests a preview of a page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/275)

Enable contentful preview for page items

---

src/components/BulkEdit/AssignOriginalPublisherPanel.tsx
src/components/BulkEdit/BulkChangeFunctions.ts
src/components/BulkEdit/BulkEditPage.tsx
src/components/BulkEdit/BulkEditPanel.tsx
src/components/BulkEdit/RequestHarvestPanel.tsx

* Changed parameter order of `ChangeColumnValue...` to a more sane (name, property) order
* Allow edit panels to have no value
* Count topic as a valid filter
* Add a panel for requesting a harvest
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/305)

BL-9558 Add "Run Harvester" command to Bulk Edit

---

src/assets/Template.svg
src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/BookDetail/DownloadToBloomButton.tsx
src/components/BookDetail/GetTemplateButton.tsx
src/components/BookDetail/TranslateButton.tsx
src/connection/LibraryQueryHooks.ts
src/localization/Code Strings.json
src/model/Book.ts

A variant of TranslateButton for templates.
The common functionality is moved to DownloadToBloomButton.txt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/313)

Implement Get Template button (BL-9584)

---

src/components/EmbeddingHost.test.ts
src/components/EmbeddingHost.tsx

Allows patterns to be specified in contentful which control which collections are allowed to be embedded.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/322)

Easier subcollection embedding, Phase 2 (BL-9720)

---

src/model/Book.ts
tsconfig.json

The build keeps adding it, so we need it committed.
Ignored two errors it causes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/352)

Add noFallthroughCasesInSwitch to tsconfig.json

---

src/components/BookCardGroup.tsx

* within child collections
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/386)

BL-10722 Allow "by-language" ordering

---

src/connection/LibraryQueryHooks.test.ts
src/connection/LibraryQueryHooks.ts

This will allow matching on the beginnings of tag values for filters
coming from Contentful, replacing the obsolete regex matching on
bookshelf values.  (which always applied but was needed for only a
handful of parent collections)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/403)

Handle trailing * for tag filter values (BL-10838)

---

src/connection/LibraryQueryHooks.ts
src/connection/LibraryQueryHooksFast.test.ts

$all:[] of a single $regex item doesn't appear to work, and isn't
needed in any case.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/406)

Fix query generation when only single tag specified (BL-10838)

---

src/components/LanguageGroup.tsx

*  Keep skinny or mobile brower from cutting off
"Languages"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/410)

BL-10888 Don't cut off "Languages"

---

src/IFilter.ts
src/model/Collections.tsx
src/model/Contentful.ts

Also remove one obsolete (now misleading) comment.  Some automatic
reformatting also snuck in.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/418)

Fix topic collections to not count rebrand books (BL-10899)

---

src/components/BookGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/416)

Fix overly lazy loading of book groups (BL-10676)

---

src/components/appHosted/AppHostedLanguageGroup.tsx

Bizarre. Reverses what I thought was the key part of allowing lang button press while input has focus. But that fix was in the wrong place: I put it on the preferred languages buttons, not the regular ones. Hypothesis: what really fixed the prior problem was putting a meaningful ID on the main language buttons, so even after restoring preferred languages, the same DOM button is still around to process the mouse-up.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/476)

Get Preferred Languages button working again (BL-11627)

---

src/components/appHosted/AppHostedLanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/480)

Fix scroll to top when filtering language for real device (BL-11687)

---

src/components/statistics/StatsOverviewScreen.tsx
src/localization/Stats Strings.json

* explanation for "people reached digitally"
* the other change matches the l10n key for a string to
the one already in the json file
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/495)

BL-11881 Add subheader to stats card label

---

src/model/Collections.tsx

In general, if a collection is a language collection, set the context language to that language (duh)
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/518)

fix BL-11469 context language lost with "all book" layout

---

src/components/Grid/GridColumns.tsx
src/connection/LibraryQueryHooks.ts

As turned sorting of the column options back on... why had I turned it off?
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/519)

BL-12824 Add "branding" to grid

---

src/components/BookDetail/ArtifactHelper.ts
src/components/BookDetail/BookOwnerControlsBox.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/548)

Changes since download-for-edit version of Desktop is now 6.0 (BL-13349)

---

src/components/AggregateGrid/AggregateGridPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/581)

Display "Unlisted Language (qaa)", not blank in language grid (BL-14280)

---

src/components/BookDetail/ArtifactVisibilityPanel/ArtifactAndChoice.stories.tsx
src/components/BookDetail/DownloadsGroup.stories.tsx
src/components/BookDetail/StaffControlsBox.tsx
src/model/ArtifactVisibilitySettings.ts
src/translations/BloomLibrary.org/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/595)

Show specific reasons for hiding provided by harvester (BL-15289)
