package.json
src/App.tsx
src/Auth0Provider.js
src/Router.ts
src/components/Admin/AdminPanel.tsx
src/components/Admin/Tag.tsx
src/components/Admin/TagsList.tsx
src/components/BookDetail/BookDetail.tsx
src/components/HarvesterArtifactUserControl/ArtifactAndChoice.tsx
src/components/HarvesterArtifactUserControl/HarvesterArtifactHelper.ts
src/components/HarvesterArtifactUserControl/HarvesterArtifactUserControl.tsx
src/components/ReadBookPage.tsx
src/connection/Connection.ts
src/connection/LibraryQueryHooks.ts
src/connection/LibraryUpdates.ts
src/connection/auth_config_dev.json
src/model/ArtifactVisibilitySettings.ts
src/model/Book.ts
src/stories/index.tsx
src/theme.ts
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/3)

Add AdminPanel

---

src/components/BookGroup.tsx
src/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/4)

Prevent clicking card when trying to click next/previous (BL-7979)

---

package.json
src/components/User/UserMenu.tsx
yarn.lock

* need test cases
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/6)

BL-8105 Show avatar

---

src/components/User/UserMenu.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/7)

BL-8105 Change User avatar default background

---

src/Router.ts
src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/LanguageLink.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/9)

language links in book detail

---

src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/LanguageGroup.tsx
src/components/LanguageLink.tsx
src/components/User/UserMenu.tsx
src/connection/LibraryQueryHooks.ts
src/connection/ParseServerConnection.ts
src/index.tsx
src/model/Book.ts
src/model/Language.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/8)

Sanitize language list (BL-7973)

---

src/components/BookDetail/ArtifactGroup.tsx
src/components/BookDetail/ArtifactHelper.ts
src/components/BookDetail/ArtifactVisibilityPanel/ArtifactAndChoice.tsx
src/components/BookDetail/ArtifactVisibilityPanel/ArtifactVisibilityPanel.tsx
src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/BookDetail/BookExtraPanels.tsx
src/model/ArtifactVisibilitySettings.ts
src/model/Book.ts
src/stories/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/12)

Update  main detail view when artifact visibility changes (BL-8110)

---

src/components/LanguageCard.tsx
src/components/LanguageGroup.tsx
src/index.css
src/stories/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/13)

Fix UI issues with Language Group (BL-8129)

---

src/components/LanguageCard.tsx
src/components/LanguageGroup.tsx
src/connection/LibraryQueryHooks.ts
src/model/Language.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/14)

Add autonyms to language cards (BL-8127)

---

src/components/Admin/TagsList.tsx
src/components/BookCard.tsx
src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/BookGroup.tsx
src/components/LanguageLink.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts
src/stories/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/11)

Add languages to the BookCard

---

src/components/LanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/15)

Stop language filter input onBlur from unfiltering list before onClick fires (BL-8138)

---

src/components/BookDetail/ArtifactVisibilityPanel/ArtifactAndChoice.tsx
src/components/CheapCard.tsx
src/components/LanguageCard.tsx
src/components/LanguageGroup.tsx
src/components/header/Header.tsx
src/index.css
src/theme.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/16)

Give message when language filter returns nothing (BL-8135)

---

src/components/BookDetail/ArtifactVisibilityPanel/ArtifactVisibilityPanel.tsx
src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/ReadOfflineButton.tsx
src/components/LanguageLink.tsx
src/components/ReadBookPage.tsx
src/connection/LibraryQueryHooks.ts
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/20)

Clean up some Typescript warnings

---

src/components/LanguageCard.tsx
src/components/LanguageGroup.tsx
src/model/Language.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/19)

Navigate to language from search with enter key (BL-8144)

---

src/Router.ts
src/components/SearchBox.tsx

* add arrow to tooltip
* make tooltip appear on focus or touch (not hover)
* enlarge font and icons
* get cancel icon to grow in place and be gray
* use different components (eliminate line)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/21)

Tooltip and Search box mods

---

src/components/BookDetail/BookExtraPanels.tsx
src/connection/LoggedInUser.ts
src/connection/ParseServerConnection.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/22)

Make visibility of book extra panels depend on moderator role (BL-8148)

---

src/components/BookCard.tsx
src/components/BookDetail/ArtifactHelper.ts
src/components/BookGroup.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/24)

Use Harvester thumbnail (BL-8116)

---

src/components/SearchBox.tsx

* and make magnifying glass click do search too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/26)

BL-8119 disable empty string search

---

src/components/BookGroup.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/27)

Repair broken process to use harvester thumbnails

---

src/components/BookDetail/MetadataGroup.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/29)

Fix importedBookSource

---

package.json
src/index.tsx
yarn.lock

still todo is figuring out source level stacks
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/32)

BL-8169 wire up sentry reporting

---

public/index.html
src/components/BookDetail/ArtifactHelper.ts
src/components/BookGroup.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

Don't look for harvested thumbnails we know we won't find
preload some fonts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/33)

Some optimizations

---

src/components/LanguageCard.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/34)

BL-8160 LIst language Tag on language card if it isn't a simple code

---

src/Router.ts
src/components/header/Header.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/35)

Handle home routing for better history management (BL-8183)

---

src/components/BookDetail/BookAnalytics.tsx
src/components/BookDetail/MetadataGroup.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/37)

The easy part of  BL-8130, shellbook downloads

---

src/components/BookDetail/ArtifactHelper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/40)

Revert sending thumbnail requests to CloudFlare

---

src/App.tsx
src/components/BookDetail/ArtifactGroup.tsx
src/components/OSFeaturesContext.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/41)

Hide Bloomd download button on IOS devices (BL-8133)

---

src/RestoreScrollPosition.ts
src/Router.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/43)

Restore Scroll Position when you go back

---

src/App.tsx
src/components/BookDetail/MetadataGroup.tsx
src/model/Bookshelf.ts
src/model/Tag.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/44)

Fix display of bookshelf names on Detail page

---

src/components/SearchBox.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/47)

BL-8196 Emptying search box then <Enter> should be like clicking "X"

---

.gitignore
src/components/BookDetail/ArtifactVisibilityPanel/ArtifactVisibilityPanel.tsx
src/components/BookDetail/BookDetail.tsx
src/components/Grid/GridColumns.tsx
src/components/Grid/GridPage.tsx
src/components/SearchBox.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/48)

More work on the grid

---

src/Router.ts
src/components/SearchBox.tsx
src/components/banners/Banners.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/50)

Improve what happens to history when you do multiple searches

---

src/components/Grid/GridColumns.tsx
src/components/Grid/GridPage.tsx
src/connection/LibraryQueryHooks.ts

Also:
Fix problem of grid not noticing that I'm a moderator
Fix paging
Limit sorting to columns where we have it working
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/52)

Grid: make sorting works across whole db, not just page

---

src/components/BookDetail/MetadataGroup.tsx
src/components/BookShelfGroup.tsx
src/components/CategoryCard.tsx
src/model/Bookshelf.test.ts
src/model/Bookshelf.ts
src/model/Tag.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/51)

Show bookshelf display names rather than keys (BL-8262)

---

src/components/Breadcrumbs.tsx
src/components/Grid/GridColumns.tsx
src/components/Grid/GridPage.tsx
src/connection/LibraryQueryHooks.ts
src/connection/SplitString.test.ts

Each commits here does a different thing, so you may want to review commit by commit.
1) increase readability around search string parsing
2) add filter control for system:Incoming
3) add count of all the matching books to the header of the grid page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/53)

Some grid improvements

---

src/IFilter.ts
src/components/Admin/HideBookControl.tsx
src/components/Admin/StaffPanel.tsx
src/components/BookDetail/BookDetail.tsx
src/components/Grid/GridColumns.tsx
src/components/Grid/GridPage.tsx
src/components/HomePage.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/55)

BL-8273 In-circulation controls for grid & staff panel

---

src/components/BookCard.tsx
src/components/BookDetail/ArtifactHelper.ts
src/components/BookDetail/BookDetailHeaderGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/57)

BL-8285 Improve Legacy Thumbnail positioning

---

src/components/ReadBookPage.tsx

* no matter where we come from, back button should
go to the current book's details page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/58)

BL-8286 Back button -> book details

---

.gitignore
src/components/BookShelfGroup.tsx
src/components/BrowseView.tsx
src/components/CategoryCard.tsx
src/components/CategoryCardGroup.tsx
src/components/FeatureGroup.tsx
src/components/FeatureHelper.tsx
src/components/FeaturePage.tsx
src/components/Grid/GridPage.tsx
src/components/HomePage.tsx
src/components/LanguageCard.tsx
src/components/LanguageFeatureList.tsx
src/stories/index.tsx
src/theme.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/56)

Add Feature group to Home page and corresponding Feature pages (BL-8132)

---

src/Router.ts
src/components/ReadBookPage.tsx
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/59)

Allow the read-book page to accept a bookLang parameter (BL-8289)

---

src/components/ReadBookPage.tsx
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/61)

Use original page size for reading books

---

src/components/HomePage.tsx
src/components/LanguageLink.tsx
src/components/Pages.tsx
src/model/Language.ts
src/stories/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/60)

Make featured bookshelf use bookshelf column; fix language display name

---

src/components/ReadBookPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/62)

BL-8286 Fix window message useEffect

---

src/components/BiblePage.tsx
src/components/BookShelfGroup.tsx
src/components/BrowseView.tsx
src/components/Covid19Page.tsx
src/components/HomePage.tsx
src/components/Pages.tsx
src/components/SpecialInterestsGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/65)

Add Special Interests to Home page (BL-8298)

---

src/components/SpecialInterestsGroup.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/66)

Make STEM button and page show math,science,environment

---

src/components/BulkEdit/AddBookshelfPanel.tsx
src/components/BulkEdit/AddTagPanel.tsx
src/components/BulkEdit/BulkChangeFunctions.ts
src/components/BulkEdit/BulkEditPage.tsx
src/components/BulkEdit/BulkEditPanel.tsx
src/components/Grid/GridControlInternal.tsx

Also fixes a bug where after a refresh you would not see the column old filters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/67)

AddTagPanel

---

src/components/Admin/StaffPanel.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/68)

Add Publisher and OriginalPublisher to staff panel

---

src/components/BiblePage.tsx
src/components/BulkEdit/AddTagPanel.tsx
src/components/BulkEdit/AssignPublisherPanel.tsx
src/components/Covid19Page.tsx
src/components/SpecialInterestsGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/69)

Use COVID-19 bookshelf instead of topic

---

src/components/Grid/GridColumns.tsx
src/components/Grid/GridControlInternal.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

Also fixed some grid columns to add to the current search instead of replacing it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/71)

Add county to grid and search

---

src/components/BookDetail/BookDetailHeaderGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/72)

Fix book lookup by phash when phash is not valid

---

src/App.tsx
src/components/BookDetail/TranslateButton.tsx
src/components/HomePage.tsx
src/components/SpecialInterestsGroup.tsx
src/components/TopicGroup.tsx
src/components/banners/HomeBanner.tsx
src/theme.ts

Make "under construction" thingy
Add poor-man's Topics list
Get rid of the featured-books row temporarily
Fix "Stem" category to show something (but math only at this point)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/74)

Cleanup Home Page

---

src/components/ByLanguageGroups.tsx
src/components/FeaturePage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/75)

Show feature pages by language rows (BL-8132)

---

src/App.tsx
src/components/BookGroup.tsx
src/components/BookShelfGroup.tsx
src/components/CardSwiper.tsx
src/components/CategoryCard.tsx
src/components/CategoryCardGroup.tsx
src/components/FeatureGroup.tsx
src/components/LanguageCard.tsx
src/components/LanguageGroup.tsx
src/components/TopicGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/77)

Add Swiper to category groups and extract our Swiper component (BL-8317)

---

src/components/BookGroup.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/82)

Enable Secondary FIlter, fix bug in tag lookup

---

src/components/BiblePage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/81)

Organize Bible page a bit more

---

src/components/ByLanguageGroups.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/83)

Consider pageCount when deciding if books are duplicates

---

src/Utilities.ts
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/84)

Escape strings before using them in regular expressions (BL-8358)

---

public/index.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/85)

Add open graph meta tags

---

src/components/ByLanguageGroups.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/86)

Retrieve all COVID-19 books, not just 100 (BL-8452)

---

src/components/FeatureGroup.tsx
src/components/FeatureHelper.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/87)

Activity page shows 'activity' and 'quiz' books (BL-8453)

---

src/connection/LibraryQueryHooks.ts
src/model/Book.test.ts
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/88)

Treat "quiz" feature as "activity" everywhere (BL-8453)

---

src/components/BookDetail/MetadataGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/89)

Clean up Book Detail's display of features and tags

---

src/components/Grid/GridColumns.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/90)

Fix duplicate strings in filter

---

package.json
src/IFilter.ts
src/Utilities.ts
src/components/Admin/StaffPanel.tsx
src/components/BookDetail/KeywordLinks.tsx
src/components/BookDetail/MetadataGroup.tsx
src/components/Grid/GridColumns.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/92)

Add "keywords" to staff panel, grid, and book detail (BL-8258)

---

src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/BookDetail/ReadOfflineButton.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/94)

Implement "Read offline" button (BL-8205)

---

src/components/OSFeaturesContext.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/95)

Hide "Translate" button on Android (BL-8204)

---

src/components/BookDetail/KeywordLinks.tsx
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/97)

Make keyword links observable

---

src/App.tsx
src/components/BookDetail/ArtifactGroup.tsx
src/components/OSFeaturesContext.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/96)

Hide (not disable) small bloomd download button when large one is shown (BL-8205)

---

.vscode/launch.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/101)

Enable debugging blorg2 with chrome on Linux (20200622)

---

src/components/BookDetail/ArtifactGroup.tsx
src/components/BookDetail/BookDetailHeaderGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/100)

Disable/hide artifacts when book's harvestState not "Done" (BL-8342)

---

src/components/banners/StandardBannerLayout.tsx

logo can shrink, and if necessary move above text
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/105)

Make banner responsive

---

src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/DeleteButton.tsx
src/components/BookDetail/ReportButton.tsx
src/connection/LibraryQueryHooks.ts
src/connection/ParseServerConnection.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/104)

Add delete book functionality (BL-8622)

---

src/components/Grid/GridColumns.tsx
src/components/Grid/GridControlInternal.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/102)

Make grid language filter pick one language

---

src/components/header/Header.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/106)

Make the main header responsive

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/108)

Report only those related books that are in circulation

---

public/embed-bloomlibrary.js
src/components/BookDetail/ReadButton.tsx
src/components/EmbeddingHost.tsx

(including bookmarking it)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/109)

Allow reading a book in embed mode

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/107)

Add support for feature:X in search

---

src/components/CollectionSubsetPage.tsx
src/components/Routes.tsx
src/model/Collections.tsx

(including search; BL-8626)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/110)

Improve titles for subset collections

---

.storybook/addons.js
package.json
src/components/BookDetail/DeleteButton.tsx
src/components/ConfirmationDialog.tsx
src/stories/addons.ts
src/stories/index.tsx
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/111)

Add confirmation dialog when deleting a book (BL-8622)

---

src/components/BookDetail/DeleteButton.tsx
src/components/ConfirmationDialog.tsx
src/stories/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/112)

Tweak UI for confirmation dialog (BL-8622)

---

src/components/BookDetail/DeleteButton.tsx
src/components/ConfirmationDialog.tsx
src/stories/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/113)

Changes after code review (BL-8622)

---

src/analytics/BloomPlayerAnalytics.ts
src/components/BookDetail/ReadButton.tsx
src/components/Footer.tsx
src/components/ReadBookPage.tsx
src/components/header/Header.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/115)

When possible, force reader to full screen and right orientation

---

src/components/statistics/ReaderSessionsChart.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/118)

Make the reader sessions chart scroll if many bars

---

src/components/BookDetail/BookStats.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/119)

Fix UI for book stats info icon (BL-8130)

---

src/components/statistics/ComprehensionQuestionsReport.tsx
src/components/statistics/useGetBookStats.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/120)

New api for comprehension question stats

---

src/components/ReadBookPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/121)

BL-8458 Don't center vertically on web

---

src/components/BookDetail/BookStats.tsx

Show a tooltip that describes the values.
Does not attempt to localize the names yet.
Limit to values we have, fade them in when available.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/128)

More work on Book overview stats

---

.vscode/launch.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/129)

Fix Linux debugging launch of chrome (20200730)

---

src/components/BookDetail/ArtifactGroup.tsx
src/components/BookDetail/ReadButton.tsx
src/components/BookDetail/TranslateButton.tsx
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/126)

Allow books to limit locations where they may be used (BL-8659)

---

src/components/statistics/StatsOverviewScreen.tsx
src/components/statistics/useGetOverviewStats.ts
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/130)

Further populate overview stats (BL-8504)

---

public/embed-bloomlibrary.js
src/components/EmbeddingHost.tsx
src/components/Routes.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/132)

Another attempt to get embedding right (BL-8702)-

---

src/components/Routes.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/131)

Make stats pages work for subcollections

---

src/analytics/BookAnalyticsInfo.ts
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/133)

Pass brandingProjectName to book level analytics

---

src/IFilter.ts
src/components/statistics/useGetOverviewStats.ts
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/136)

Filter on publisher, originalPublisher, and get derivatives of a collection (BL-8504)

---

src/components/ArtifactHelper.test.ts
src/components/BookDetail/ArtifactHelper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/137)

Make artifact paths match what Harvester produces

---

src/export/freeLearningIO.ts

Move some logic to ArtifactHelper
Revert incomplete fix for special characters
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/138)

Add an epub url column to freeLearningIO CSV

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/142)

Prevent extra request to api.bloomlibrary.org/v1/stats (BL-8850)

---

src/components/BookDetail/ArtifactHelper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/144)

Fix URL for PDFs where name has special characters

---

src/components/ReadBookPage.tsx
src/components/Routes.tsx
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/145)

Hide the player back/more button when coming from detail view (BL-8631)

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/146)

Improve code safety by cloning object before modifying it (BL-8850)

---

src/components/ReadBookPage.tsx
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/150)

Let bloom-player show the full-screen button for reading books (BL-8834)

---

src/components/ReadBookPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/151)

Get full-screen working for the embed test (BL-8834)

---

src/components/TestEmbedding.tsx
src/stories/index.tsx
src/testEmbedOneBlorgBook.htm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/152)

More fullscreen settings on iframes (BL-8834)

---

src/components/Routes.tsx
src/components/RowOfCollectionCards.tsx
src/model/Collections.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

Our contentful model allows cards which are pages, but the code didn't know about that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/153)

Make "page" collections work

---

src/IFilter.ts
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/148)

Limit derivative collections to books not in parent (BL-8858)

---

src/components/BulkEdit/AssignOriginalPublisherPanel.tsx
src/components/BulkEdit/BulkEditPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/154)

BL-8880 Add BulkEdit Original Publisher

---

src/connection/LibraryQueryHooks.ts

* fixes Guatemala stats view
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/155)

BL-8901 Guard against null

---

src/components/ReadBookPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/162)

Catch back and other in-SPA events in book read for analytics (BL-8804)

---

src/components/WindowsInstallerDownloads.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/166)

Fix requirements link and only show release notes link if exists

---

src/components/ReadBookPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/167)

Fix a Lint warning

---

src/components/CollectionPage.tsx
src/components/CollectionSubsetPage.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/168)

BL-8955 Allow contentful to control number of rows

---

src/index.tsx

Before this will do any good, a change has to be made to the bucket, which is described in the comments.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/169)

Fix BL-8969 Spurious 404 errors

---

src/components/ReadBookPage.tsx
src/components/Routes.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/170)

Fix bug if title contains "%" characters (BL-9041)

---

src/components/RowOfCollectionCards.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/171)

BL-9080 preserve order of contentful cards

---

src/model/Collections.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/172)

Sort the topics list (BL-9089)

---

src/Utilities.ts
src/components/BookCardGroup.tsx
src/components/CardGroup.tsx
src/components/CardSwiper.tsx
src/components/CollectionCard.tsx
src/components/LanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/175)

Improve navigation accessibility (BL-8165)

---

src/components/CollectionCard.tsx
src/components/User/UserMenu.tsx
src/model/Collections.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/177)

BL-8964 Create my-books collection

---

src/components/Grid/GridControlInternal.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/179)

Change collection search facet to just "collection" (BL-8880)

---

src/components/BulkEdit/BulkEditPanel.tsx
src/components/Grid/GridControlInternal.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/180)

Fix bugs in using search for collections (BL-8880)

---

src/App.tsx
src/components/BookCardGroup.tsx
src/components/BookGroup.tsx
src/components/CardGroup.tsx
src/components/Footer.tsx
src/components/LanguageGroup.tsx
src/components/SearchBox.tsx
src/components/header/Header.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/181)

Add aria-landmark (role) attributes (BL-8967)

---

src/components/BookCard.tsx
src/components/BookCardGroup.tsx
src/components/BookGroup.tsx
src/components/CardGroup.tsx
src/components/CardSwiper.tsx
src/components/CheapCard.tsx
src/components/CollectionCard.tsx
src/components/LanguageCard.tsx
src/components/LanguageFeatureList.tsx
src/components/LanguageGroup.tsx
src/components/header/Header.tsx
src/theme.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/182)

Get main page and hopefully most others passing lighthouse (BL-8968)

---

src/connection/UseContentful.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/185)

Use localized Contentful content (BL-9072)

---

src/components/Routes.tsx

* link on Create page button now works
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/187)

BL-9073 Get about page linked

---

src/App.tsx
src/components/Footer.tsx
src/components/header/Header.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/189)

Make Player work in Safari (BL-9144)

---

src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/FeaturesGroup.tsx
src/components/BookDetail/MetadataGroup.tsx
src/components/FeatureHelper.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/188)

Detail shows features as icon buttons (BL-8131)

---

src/components/BookDetail/BookDetail.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/190)

Hide the "How to translate" button (BL-9201)

---

src/components/ContentfulMarkdownPart.tsx
src/components/pages/ContentfulMultiPartPage.tsx
src/components/pages/ContentfulPage.tsx
src/index.css

* add colored bands alternating per section
* make secondary markdown float to right
* update several sections to be more like original
About page
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/191)

BL-9073 More About page changes

---

src/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/192)

Only apply 200px width for img in the right context (BL-9136)

---

public/Bloom Library Strings.csv
src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/BookDetail/BookThumbnail.tsx
src/components/BookDetail/ReportButton.tsx
src/components/BookDetail/ReportDialog.tsx
src/connection/ParseServerConnection.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/193)

Implement reporting concerns about a book (BL-8856)

---

src/components/BookDetail/ReportDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/195)

Tweaks for report dialog (BL-8856)

---

src/components/CollectionPage.tsx
src/components/CollectionSubsetPage.tsx

Also set number of rows for png-rise to 4 instead of 999.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/173)

Fix broken "See more of these books" button (BL-8953)

---

src/components/Breadcrumbs.tsx
src/components/ContentfulMarkdownPart.tsx
src/components/FeatureMatrix.tsx
src/components/ListOfBookGroups.tsx
src/components/WindowsInstallerLink.tsx
src/components/pages/ContentfulPage.tsx
src/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/196)

Feature Matrix Page

---

src/components/ContentfulMarkdownPart.tsx
src/index.css

* change color bands
* center h1 headers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/197)

BL-9073 About page tweaks

---

src/App.tsx
src/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/199)

BL-9224 Narrow screen page width problem

---

src/components/CheapCard.tsx
src/components/CollectionCard.tsx
src/components/RowOfCollectionCards.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/198)

Allow thin row of cards

---

src/components/BookDetail/ArtifactGroup.tsx
src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/BookDetail/BookStats.tsx
src/components/BookDetail/MetadataGroup.tsx
src/components/ButtonRow.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/201)

Fix list styles after removing global ul style (BL-9233)

---

src/model/Contentful.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/203)

BL-9232 allow "tag" filter from contentful

---

src/components/BookCardGroup.tsx
src/components/CardGroup.tsx
src/components/RowOfCards.tsx
src/components/StoryCard.tsx
src/components/banners/Blurb.tsx
src/model/Collections.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/205)

Side descriptions

---

src/components/pages/ContentfulPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/207)

Use label as the title if the markdown content file doesn't seem to have one

---

public/embed-bloomlibrary.js
src/App.tsx
src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/FeaturesGroup.tsx
src/components/EmbeddingHost.tsx
src/components/Routes.tsx
src/components/TestEmbedding.tsx
src/embedded.tsx
src/index.tsx
src/stories/index.tsx
src/stories/testembed.htm

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/194)

Get rid of /embed/embedSettingsName prefix for embedding (BL-8839)

---

src/components/Grid/GridColumns.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/209)

BL-9240 Add typeahead to "other tag" in grid

---

src/components/ByLanguageGroups.tsx
src/components/FeatureHelper.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/215)

Don't show items in language list that lack feature in lang (BL-9257)

---

src/components/Admin/StaffMultiChoosers.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/216)

Add new tags to tag list immediately (BL-9241)

---

src/components/Admin/StaffMultiChoosers.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/219)

Sort tags after adding new ones (BL-9241)

---

src/model/Collections.tsx
src/model/InternationalizedContent.tsx

* and update a comment to reflect Features
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/222)

BL-9252 Fix "Other" topic bug

---

src/IFilter.ts
src/components/Admin/StaffPanel.tsx
src/components/ByLanguageGroups.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts
src/stories/index.tsx

* and to search, filter possibilities
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/224)

BL-9260 Add "Edition" to Staff panel data

---

src/components/User/UserMenu.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/228)

BL-9280 Remove unimplemented Profile

---

src/components/banners/Blurb.tsx

* fixes Guatemala and Enabling Writers
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/223)

BL-9263 Make Collection desc. scroll vertically

---

src/components/ByLanguageGroups.tsx

* take which features the book has into account
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/227)

BL-9277 Improve collapsing algorithm

---

src/components/SearchBox.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/229)

Allow search by language name (BL-9288)

---

src/components/CollectionPage.tsx
src/components/LanguageCard.tsx
src/components/SearchBox.tsx
src/localization/Code Strings.json
src/model/Language.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/230)

Various cleanup and fixes, mostly l10n-related

---

src/components/ReadBookPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/234)

Work around bizarre endless spinner on 'back' from player (BL-8866)

---

src/components/ReleaseNotes.tsx
src/components/Routes.tsx
src/components/WindowsInstallerDownload.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/233)

BL-9222 Show Release Notes page

---

src/components/ByLanguageGroups.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/235)

Add row to ByLanguage for SL books in unknown sign language (BL-9300)

---

src/components/FeatureHelper.tsx
src/components/SearchBox.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/236)

Allow search by feature label (BL-9299)

---

src/components/BlorgLink.tsx
src/components/BookDetail/DownloadShellbookDialog.tsx
src/components/BookDetail/TranslateButton.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/237)

Add UI around shellbook download (BL-8111)

---

src/components/BookDetail/DownloadShellbookDialog.tsx
src/theme.tsx

Make all muidialogs have a consistent margin around the outside, drop the grey in the action area.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/238)

Dialog layout tweaks

---

src/components/BookDetail/DownloadPreflightDialog.tsx
src/components/BookDetail/DownloadingShellbookDialog.tsx
src/components/BookDetail/TranslateButton.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/239)

Finish adding shellbook download dialogs (BL-8111)

---

src/components/ReadBookPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/242)

Convert the history problem alert to console.log

---

src/components/BlorgLink.tsx

Now limited to just embedded scenarios
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/245)

Dial back opening new tabs

---

src/components/LanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/241)

Use larger font in language search box (BL-9204)

---

src/components/ReadBookPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/248)

Only go auto-fullscreen on mobile (BL-8866)

---

src/components/BlorgLink.tsx
src/components/BookDetail/HowToPrintButton.tsx
src/components/CheapCard.tsx
src/components/WindowsInstallerLink.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/240)

Fix external links on CheapCards (BL-9310)

---

src/components/BookCard.tsx
src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/ReadButton.tsx
src/components/ReadBookPage.tsx

* send correct title to BP
* don't catch message as error in ReadBookPage that is meant for
embed-bloomlibrary.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/247)

BL-9307 BL part

---

src/components/BookCardGroup.tsx
src/components/Breadcrumbs.tsx
src/components/ByLevelGroups.tsx
src/components/ByTopicsGroups.tsx
src/components/CollectionCard.tsx
src/components/CollectionPage.tsx
src/components/CollectionSubsetPage.tsx
src/components/statistics/CollectionStatsPage.tsx
src/components/statistics/QueryDescription.tsx
src/localization/Code Strings.json
src/localization/CollectionLabel.tsx
src/localization/Stats Strings.json
src/model/Collections.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/231)

Add some missing internationalizations

---

src/components/statistics/CollectionStatsPage.tsx
src/components/statistics/StatsCard.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/249)

Fix formatting on stats page, especially card height (BL-9343)

---

src/components/Footer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/250)

Fix footer height (BL-9348)

---

public/index.html
src/components/CardSwiper.tsx
src/components/CollectionPage.tsx
src/components/banners/ContentfulBanner.tsx
src/components/banners/StandardBannerLayout.tsx
src/model/CacheProvider.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/254)

More performance tweaks

---

src/components/BlorgMarkdown.tsx
src/components/ColoredBlock.tsx
src/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/255)

Add ColoredBlock component to support new About Bloom page (BL-9381)

---

src/components/banners/Blurb.tsx
src/components/banners/ImageCreditsTooltip.tsx
src/components/banners/ImageOnRightBannerLayout.tsx
src/components/banners/StandardBannerLayout.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/256)

Tweak banner images and image credits

---

src/connection/UseContentful.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/257)

Prevent getLocales from being a performance bottleneck

---

src/components/Attribution.tsx
src/components/BlorgMarkdown.tsx
src/components/Testimonial.tsx
src/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/258)

Add Testimonial and Attribution for new About Bloom page (BL-9381)

---

src/components/Attribution.tsx
src/components/BlorgMarkdown.tsx
src/components/ColoredBlock.tsx
src/components/Columns.tsx
src/components/Testimonial.tsx
src/components/pages/ContentfulMultiPartPage.tsx
src/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/261)

Add Columns (and Column) component for About page (BL-9381)

---

src/Utilities.ts
src/components/Routes.tsx
src/components/User/LoginDialog.tsx
src/components/User/UserMenu.tsx
src/components/statistics/CollectionStatsPage.tsx
src/components/statistics/CollectionStatsPageCodeSplit.tsx
src/firebase/StyledFirebaseAuthCodeSplit.tsx
src/firebase/firebase.ts
src/index.tsx

Code splits for stats and firebase
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/262)

More performance improvements

---

src/analytics/Analytics.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/263)

Delay loading analytics till after page is stable

---

package.json
src/Utilities.ts
src/components/statistics/CollectionStatsPage.tsx
src/components/statistics/ReaderSessionsChart.tsx
src/components/statistics/ScreenOptionsSelect.tsx
src/components/statistics/StatsCard.tsx
src/components/statistics/StatsInterfaces.ts
src/connection/LibraryQueryHooks.ts
src/model/Collections.tsx
yarn.lock

Moved various small chunks of code out of ReaderSessionsChart to keep it and dependencies out of initial load. Restrict fetched collection fields to the ones we need.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/264)

More optimizations

---

src/components/MoreCard.tsx

Copy/pasted from BookCard.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/265)

Make MoreCard same height as BookCard (BL-9400)

---

src/components/banners/ContentfulBanner.tsx

Hard-coded banner height
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/266)

Reduce content shift on home page (BL-9390)

---

src/components/CardSwiper.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/268)

Avoid generating too many cards in swiper

---

src/connection/UseContentful.tsx
src/model/Collections.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/269)

Get and cache just the collections we need

---

yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/270)

Update bloom-player to latest in blorg2 (20210115)

---

src/components/BookCard.tsx
src/components/BookCardGroup.tsx
src/components/CardSwiper.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/271)

Fix swiper width when in a flex column

---

src/components/BookCardGroup.tsx
src/components/BookGroup.tsx
src/theme.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/272)

Shrink space between rows in mobile (BL-9413)

---

src/components/CardSwiper.css
src/components/CardSwiper.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/273)

Make swiper fade on the right (BL-9386)

---

src/components/BookCard.tsx
src/components/CollectionCard.tsx
src/components/LanguageCard.tsx
src/components/SmartTruncateMarkup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/274)

Tweak positioning and max length of various labels (BL-9412 and 9417)

---

src/components/StoryCard.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/277)

Limit number of lines of StoryCard excerpt (BL-9412)

---

src/components/BookCard.tsx
src/components/BookCardGroup.tsx
src/components/BookDetail/BookExtraPanels.tsx
src/components/BookGroup.tsx
src/components/CardGroup.tsx
src/components/CardSwiper.tsx
src/components/CheapCard.tsx
src/components/CollectionCard.tsx
src/components/LanguageCard.tsx
src/components/LanguageGroup.tsx
src/components/MoreCard.tsx
src/components/RowOfCards.tsx
src/components/StoryCard.tsx
src/theme.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/278)

Make card spacing consistent everywhere (BL-9399)

---

src/components/CardSwiper.tsx

Prevents them disappearing while scrolling off.
Also has a one-line fix for not being able to click on the card under the fade overlay (BL-9386)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/279)

Keep cards before the last visible one real (BL-9421)

---

src/components/CollectionPage.tsx
src/components/PageNotFound.tsx
src/components/Routes.tsx
src/components/statistics/CollectionStatsPage.tsx
src/components/statistics/DataStudioDasboardScreen.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/280)

Improvements for transitioning from legacy urls (BL-9426)

---

src/components/BookCardGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/281)

Get swiper working on create page

---

src/components/LanguageCard.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/282)

Allow two lines for secondary Language name (BL-9412)

---

src/components/BlorgLink.tsx
src/components/CollectionPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/284)

BL-9427 Fix mailto links and remove an unused import

---

package.json
src/components/markdown/AllBloomInstallers.tsx
src/components/markdown/BlorgMarkdown.tsx
yarn.lock

The xml parser that this adds is the smallest I could find: 1.8kB minified.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/288)

Add <AllBloomInstallers> component

---

src/components/CollectionCard.tsx
src/components/LanguageCard.tsx
src/theme.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/287)

Adjust padding for small Collection or Language cards (BL-9423)

---

src/components/BulkEdit/BulkEditPage.tsx
src/connection/LoggedInUser.ts
src/model/ArtifactVisibilitySettings.ts
src/model/Book.ts

I simply ran npx mobx-undecorate on the src directory
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/289)

Fix mobx after breaking upgrade to v6 (BL-9437, BL-9438, BL-9440)

---

src/connection/LoggedInUser.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/290)

Replace a deprecated Mobx method (BL-9437, BL-9438 etc)

---

src/components/PageNotFound.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/291)

Ensure minimal margin around text of Page Not Found page (BL-9426)

---

src/App.tsx

* simplifies other code too
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/293)

Fix mobx to use actions where needed

---

src/components/BookDetail/TranslateButton.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/294)

Fix layout of Translate Button for French (BL-9452)

---

src/components/SearchBox.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/295)

Fix unclickable portion of search bar on smaller screens (BL-9454)

---

src/components/CardGroup.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/296)

Do not display heading for "Simple Page Links" collections (BL-9476)

---

src/components/banners/Blurb.tsx
src/model/Collections.tsx
src/model/ContentInterfaces.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/297)

Remove obsolete banner "blurb"

---

src/components/Routes.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/299)

Fix broken links from BloomDesktop containing hashes (BL-9508)

---

src/components/BookDetail/ArtifactVisibilityPanel/ArtifactAndChoice.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/300)

Prevent extraneous saves to book from artifact control (BL-9507)

---

src/components/Routes.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/301)

Reroute some legacy URLs to the new library sites (BL-9525)

---

src/components/Admin/StaffPanel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/302)

Allow staff to request harvesting a book (BL-8287)

---

src/components/Admin/StaffPanel.tsx
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/303)

Requesting a book harvest actually gets through to Parse (BL-8287)

---

src/components/Admin/StaffPanel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/304)

Tweak relative positioning of Request Harvesting control (BL-8287)

---

src/components/Grid/GridExport.ts
src/export/exportData.tsx

Tried to add Unicode BOM as well, but that doesn't work in Chrome.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/309)

Tweak CSV export to handle newlines in titles (BL-9559)

---

src/components/CheapCard.tsx
src/components/Routes.tsx
src/components/StoryCard.tsx
src/theme.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/306)

BL-9601 improve styling of card hover

---

src/components/BookCardGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/310)

Allow markdown in collection descriptions (BL-9603)

---

src/components/Grid/GridColumns.tsx
src/components/Grid/GridExport.ts
src/components/statistics/StatsInterfaces.ts
src/components/statistics/useGetBookStats.ts
src/connection/LibraryQueries.ts
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

Any remaining statistics columns could be added easily if wanted.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/311)

Add two statistics columns to grid for display and export (BL-9602)

---

src/assets/Template.svg
src/components/BookDetail/GetTemplateButton.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/315)

Fix template icon colors (BL-9584)

---

src/components/Grid/GridColumns.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/316)

Allow grid filtering on publisher and originalPublisher

---

src/components/Admin/StaffPanel.tsx
src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/BookDetail/DownloadToBloomButton.tsx
src/components/BookDetail/KeywordLinks.tsx
yarn.lock

* fix warning in StaffPanel
* fix warning in KeywordLinks
* remove unused imports in 2 files
* upgrade react-select to avoid another warning
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/318)

Fix some warnings

---

src/connection/LibraryQueryHooks.test.ts
src/connection/LibraryQueryHooks.ts
src/connection/SplitString.test.ts

* 2 commits - first is fixing various warnings, second is the actual fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/317)

BL-9697 Fix publisher/originalPublisher searches

---

public/embed-bloomlibrary.js
src/components/BlorgLink.tsx
src/components/EmbeddingHost.tsx
src/components/TestEmbedding.tsx

Based on passing in bl-domain and checking DomainEmbeddingSettings in contentful
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/319)

Easier subcollection embedding, Phase 1 (BL-9720)

---

src/components/OSFeaturesContext.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/323)

Fix detection of Linux desktop for Firefox browser (BL-9728)

---

src/model/Book.test.ts
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/320)

Change quiz to be subcategory of activity (BL-9682)

---

src/components/BookDetail/MetadataGroup.tsx
src/connection/LibraryQueryHooks.ts
src/localization/Code Strings.json
src/model/Book.ts

* new info was in parsedb, so a bit trickier to get
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/321)

BL-9514 Replace last updated with last uploaded

---

src/components/BookCount.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/326)

If the collection filter is empty, disable book count (BL-9742)

---

src/components/SearchBox.tsx
src/model/SpecialSearch.test.ts
src/model/SpecialSearch.ts

* removed old tooltip stuff we aren't using
* pulled all special searches out to a separate file
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/325)

BL-9751 1st steps toward Phase 1

---

src/components/BookCount.tsx
src/components/banners/StandardBannerLayout.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/327)

Fix book count not showing on home page (BL-9742)

---

src/components/Admin/StaffPanel.tsx
src/components/BookDetail/ArtifactVisibilityPanel/ArtifactAndChoice.tsx

* was a bit tricky to find a way that worked with both urls
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/328)

BL-9772 Unsmush book detail controls in create

---

src/components/BlorgLink.tsx
src/components/BookDetail/LicenseLink.tsx
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/329)

Show licenseNotes when custom License clicked (BL-9713)

---

src/components/BookDetail/ArtifactVisibilityPanel/ArtifactAndChoice.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/330)

Fix formatting if long text in ArtifactAndChoice (BL-9726)

---

LICENSE
src/components/Footer.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/332)

Update copyright year (BL-9829)

---

src/components/Grid/GridColumns.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/333)

BL-9836 Blorg Grid: Add features, harvestState, and harvestStartAt

---

.vscode/settings.json
src/components/Admin/StaffPanel.tsx
src/components/BlorgLink.tsx
src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/MissingFontBlock.tsx
src/localization/Code Strings.json
src/model/Book.ts

screenshot: https://issues.bloomlibrary.org/youtrack/issue/BL-9999
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/338)

BL-9999 When harvest failed because of font, give a link to the form

---

src/components/FeatureHelper.tsx
src/components/FeatureLevelBar.tsx
src/localization/Code Strings.json
src/localization/Topics And Features.json
src/localization/readme-l10n.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/340)

BL-10041 Book level UI improvements

---

src/components/CollectionPage.tsx
src/components/RowOfCards.tsx
src/model/Collections.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/342)

BL-10063 option to make child collection rows wrap

---

src/components/Routes.tsx
src/components/reports/CollectionReport.tsx
src/components/reports/CollectionReportSplit.tsx
src/connection/LibraryQueries.ts
src/connection/LibraryQueryHooks.ts
src/localization/Stats Strings.json
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/343)

Add pratham/report page (BL-9896)

---

src/components/statistics/BookStatsReport.tsx
src/components/statistics/ComprehensionQuestionsReport.tsx
src/components/statistics/ReaderSessionsChart.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/346)

Fix stats for collections with no filters (BL-10126)

---

src/components/reports/CollectionReport.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/345)

Add CSV export to collection report and align page title (BL-9896)

---

src/components/reports/CollectionReport.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/350)

Fix a couple of warnings (20210629)

---

src/components/BulkEdit/BulkChangeFunctions.ts
src/components/BulkEdit/BulkEditPage.tsx
src/components/BulkEdit/HideBooksPanel.tsx
src/components/Grid/GridColumns.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/347)

Add HideBooksPanel to Bulk Edit

---

src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/BookNotice.tsx
src/components/BookDetail/BookProblemNotice.tsx
src/components/BookDetail/HarvestProgressNotice.tsx
src/components/BookDetail/MissingFontNotice.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/351)

BL-10167 Add notices if the harvester has not tried to process a book

---

src/components/BulkEdit/BulkEditPanel.tsx
src/components/BulkEdit/HideBooksPanel.tsx
src/components/Grid/GridColumns.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/353)

BL-10180 Allow un-hiding books in bulk edit

---

src/components/ReadBookPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/354)

More robust exitFullscreen

---

src/IFilter.ts
src/components/CollectionCard.tsx
src/components/banners/StandardBannerLayout.tsx
src/connection/LibraryQueryHooks.test.ts
src/connection/LibraryQueryHooks.ts
src/model/Collections.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/358)

Get total books counts for parent collections (BL-10187)

---

src/components/CardGroup.tsx
src/model/Collections.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/361)

Add CardGroup book count (BL-10285)

---

src/components/BookCard.tsx
src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/BookDetail/MetadataGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/360)

Prevents crashes in case of pathological book (BL-10286)

---

src/components/BookDetail/BloomPubIcon.tsx
src/components/BookDetail/DownloadsGroup.tsx
src/components/OSFeaturesContext.tsx

* also tweaked OSFeatures so simulating an iPhone in
Chrome works correctly
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/359)

BL-10249 Tweak UI of desktop BR link

---

src/components/BookDetail/DownloadsGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/363)

BL-10249 Fix Get BR link hiding

---

src/model/SpecialSearch.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/364)

Match "Chinese, Simplified" when searching for "Chinese" (BL-10301)

---

src/components/CollectionPage.tsx
src/model/Collections.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/368)

BL-10354 Sponsorship Row for Collections

---

src/components/BulkEdit/AddFeaturePanel.tsx
src/components/BulkEdit/BulkChangeFunctions.ts
src/components/BulkEdit/BulkEditPage.tsx
src/connection/LibraryQueryHooks.ts

- Change useGetTagList() to work properly even if more than 1000 tags
- Add to Bulk Edit page a "Add Features"  option (BL-10359)
- Add Typescript typings to useLibraryQuery.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/370)

Add to Bulk Edit page a "Add Features"  option (BL-10359)

---

src/components/Grid/GridExport.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/379)

Include book url in csv export

---

src/components/CollectionSubsetPage.tsx
src/model/Collections.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/380)

Fix More card for facet searches (BL-10618)

---

src/components/Grid/GridExport.ts
src/export/exportData.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/381)

Make urls in csv export clickable (BL-10619)

---

src/components/BookDetail/ArtifactHelper.ts
src/components/BookDetail/ArtifactVisibilityPanel/ArtifactAndChoice.tsx
src/components/BookDetail/DownloadsGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/378)

Add tooltips to artifact buttons (BL-9773)

---

src/components/AllCard.tsx
src/components/BookCardGroup.tsx
src/components/Breadcrumbs.tsx
src/components/CollectionSubsetPage.tsx
src/components/MoreCard.tsx
yarn.lock

Also update react-truncate-markup for better performance
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/382)

Allow "more" card to show all (BL-10617)

---

src/components/BookDetail/BookStats.tsx
src/connection/ApiConnection.ts
src/connection/LibraryQueries.ts
src/connection/LibraryQueryHooks.ts
src/export/freeLearningIO.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/384)

Bring book stats code into alignment with changes in Azure function (BL-10680)

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/385)

BL-10745 Allow "language:xyz" in search

---

src/components/BookCardGroup.tsx
src/components/CardGroup.tsx
src/components/CollectionLayout.tsx
src/components/CollectionPage.tsx
src/model/Collections.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/387)

Allow subcollections to use layouts (BL-10722)

---

src/components/LanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/388)

Don't show language cards with no books (BL-10796)

---

package.json
src/components/User/UserMenu.tsx
src/firebase/StyledFirebaseAuthCodeSplit.tsx
src/firebase/firebase.ts
yarn.lock

Note, currently using the "compat" API of firebase v9. It's a TODO to switch to their currently API that supports tree-shaking.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/389)

Upgrade Node to LTS which necessitated upgrade to Firebase

---

src/components/BookDetail/LicenseLink.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/391)

Properly handle "ask" license on book detail page (BL-10806)

---

src/components/banners/Blurb.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/392)

BL-10823 Shrink H1 in mobile banners

---

src/components/CollectionPage.tsx
src/components/banners/DownloadBundleButton.tsx
src/localization/Code Strings.json
src/model/Collections.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/394)

BL-10800 DownloadAll Buttons

---

src/components/ArtifactHelper.test.ts
src/components/BookDetail/ArtifactHelper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/393)

Decode book name, don't sanitize it (BL-10406)

---

src/localization/Code Strings.json
src/model/ArtifactVisibilitySettings.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/398)

Disable PDF download if it wasn't uploaded (BL-10816)

---

src/components/CollectionPage.tsx
src/model/Collections.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

Merge only *after* the SEOCanonical one
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/396)

BL-10834 SEO on language pages

---

src/components/Admin/MultiChooser.tsx
src/components/Admin/StaffMultiChoosers.tsx

This is step one of the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/399)

Disable bookshelf chooser in staff panel (BL-10838)

---

src/connection/LibraryQueryHooks.ts
src/connection/SplitString.test.ts

* added 'facet' for brandingProjectName
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/401)

BL-10850 Fix brandingProjectName search

---

src/components/BulkEdit/AddBookshelfPanel.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/402)

Disable the Add Bookshelf control in bulk edit (BL-10838)

---

src/components/BookCardGroup.tsx
src/components/BookCount.tsx
src/components/BookGroup.tsx
src/components/Breadcrumbs.tsx
src/components/CollectionInfoWidget.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/404)

BL-10861 Let staff see filters and urlkeys

---

src/connection/LibraryQueryHooks.ts
src/connection/LibraryQueryHooksFast.test.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/407)

Handle derivedFrom filters for tags as well as bookshelves (BL-10838)

---

src/components/statistics/CollectionStatsPage.tsx
src/components/statistics/StatsCredits.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/409)

Add attribution for ip2location. (BL-10736)

---

src/components/CollectionInfoWidget.tsx
src/connection/LoggedInUser.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/414)

BL-10901 Fix collectionWidget after refresh

---

src/components/BookCardGroup.tsx
src/components/CollectionLayout.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/415)

Remove duplicate headings/counts from RISE-PNG (BL-10859)

---

src/connection/LibraryQueryHooks.ts

Some random reformatting seems to have occurred as well.  I don't why this
happened.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/419)

Fix missing languages for book cards (BL-10906)

---

public/robots.txt

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/421)

Add non-production robots.txt (BL-10905)

---

src/components/BookDetail/MetadataGroup.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/420)

Localize rebranding tooltip (BL-10865)

---

src/components/BookCount.tsx
src/components/BookGroup.tsx
src/components/Breadcrumbs.tsx
src/components/ByLanguageGroups.tsx
src/components/CardRow.tsx
src/components/CollectionCard.tsx
src/components/CollectionInfoWidget.tsx
src/components/CollectionLayout.tsx
src/components/CollectionSubsetPage.tsx
src/components/banners/ImageOnRightBannerLayout.tsx
src/components/banners/StandardBannerLayout.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/417)

Pass collection instead of filter whenever possible (BL-10900)

---

src/model/Collections.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/424)

Add rebrand:No to the generated topics collection filters (BL-10899)

---

src/components/BookDetail/MetadataGroup.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/428)

Tweak messages for first and last uploaded dates (BL-9514)

---

src/components/CollectionCard.tsx
src/model/Collections.tsx
src/model/ContentInterfaces.ts
src/model/Contentful.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/434)

Add optional country to collection card (BL-10188)

---

src/components/BookDetail/DownloadPreflightDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/435)

Handle very long titles better in download dialog (BL-9847)

---

src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/appHosted/AppHostedDownloadButton.tsx
src/components/appHosted/AppHostedLanguageGroup.tsx

- sort langs by primary name
- larger download size
- white space around download button
- hide "books that may be translations"
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/442)

Tweak layout of appHosted mode

---

babel.config.js
package.json
src/App.tsx
src/Utilities.ts
src/components/BookCard.tsx
src/components/BookCardGroup.tsx
src/components/BookGroup.tsx
src/components/ByLanguageGroups.tsx
src/components/CardSortingTroubleshootingInfo.tsx
src/components/CollectionInfoWidget.tsx
src/components/SortInfo.tsx
src/components/User/UserMenu.tsx
src/connection/LibraryQueries.ts
src/connection/LibraryQueryHooks.test.ts
src/connection/LibraryQueryHooks.ts
src/connection/LibraryQueryHooksFast.test.ts
src/connection/LoggedInUser.ts
src/connection/sorting.test.ts
src/connection/sorting.ts
src/model/Book.ts
src/model/ContentInterfaces.ts
src/model/Contentful.ts
yarn.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/441)

BL-11137 Book Sorting

---

.vscode/settings.json
package.json
src/components/BulkEdit/AssignNotesPanel.tsx
src/components/BulkEdit/BulkEditPage.tsx
src/components/Grid/GridColumns.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/444)

BL-11412 Bulk Edit Notes

---

src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/BookDetail/GetBloomReaderButton.tsx
src/components/Routes.tsx
src/components/appHosted/AppHostedDownloadButton.tsx
src/components/appHosted/AppHostedDownloadingPage.tsx
src/components/appHosted/AppHostedLanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/445)

Hide app-hosted download button if bloomPUB is not available (BL-11420)

---

src/components/UnderConstruction.tsx
src/components/appHosted/AppHostedUtils.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/447)

Don't show "next" version banner in app-hosted mode

---

src/components/appHosted/AppHostedDownloadButton.tsx
src/components/appHosted/AppHostedLanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/448)

Fix preferred language list (BL-11407)

---

src/components/BookDetail/BookDetail.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/449)

Treat app-hosted link to normal detail page as external (BL-11409)

---

package.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/450)

Require active Node LTS version or higher (BL-11342)

---

src/components/BookDetail/BookDetail.tsx
src/components/Routes.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/451)

Fix issues with page titles in app-hosted mode (BL-11434)

---

src/components/BlorgLink.tsx
src/components/BookDetail/BookDetail.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/453)

Fix app-hosted external links (BL-11409)

---

src/components/BookDetail/BookDetail.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/454)

Add message about how to update a book (BL-9774)

---

src/components/LanguageCard.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/455)

In app-hosted mode, filter books without bloomPub (BL-11421)

---

src/components/Grid/GridColumns.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/457)

Don't crash in grid filtering on title (BL-11475)

---

src/components/Footer.tsx
src/components/FooterCodeSplit.tsx
src/components/Routes.tsx
src/components/User/UserMenu.tsx
src/components/User/UserMenuCodeSplit.tsx
src/components/header/Header.tsx
src/components/markdown/BlorgMarkdown.tsx
src/components/markdown/FeatureMatrix/Feature.tsx
src/components/markdown/FeatureMatrix/FeatureCodeSplit.tsx
src/components/markdown/FeatureMatrix/FeatureGroup.tsx
src/components/markdown/FeatureMatrix/FeatureGroupCodeSplit.tsx
src/components/markdown/FeatureMatrix/FeatureMatrix.tsx
src/components/markdown/FeatureMatrix/FeatureMatrixCodeSplit.tsx
src/index.tsx
src/model/RouterContent.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/458)

Code-splitting to reduce app-hosted load time (BL-11515)

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/459)

Fix filtering by title to work properly in grid (BL-11475)

---

src/components/BookCount.tsx
src/components/statistics/QueryDescription.tsx
src/components/statistics/StatsCard.tsx
src/localization/Stats Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/463)

BL-11536 Clean up stats cards to handle large numbers

---

src/components/ArtifactHelper.test.ts
src/components/BookDetail/ArtifactHelper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/464)

Don't decode book name from URL (BL-11556)

---

src/components/CheapCard.tsx
src/components/LanguageCard.tsx
src/components/appHosted/AppHostedLanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/466)

Invert colors of preferred language cards (BL-11578)

---

src/components/BookDetail/MetadataGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/467)

Fix UI when lastUploaded is undefined (BL-11591)

---

src/components/appHosted/AppHostedLanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/469)

Hide preferred languages when lang input has focus (BL-11575)

---

src/components/LanguageCard.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/468)

Make sure at least two languages fit on a row (BL-11573)

---

src/components/LanguageGroup.tsx
src/components/appHosted/AppHostedLanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/470)

Fix language count to not include unused languages

---

src/components/LanguageCard.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/471)

Limit max width of language card to app hosted (BL-11573)

---

src/components/appHosted/AppHostedLanguageGroup.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/472)

Add labels to language card groups (BL-11589)

---

src/components/CardSortingTroubleshootingInfo.tsx
src/components/CollectionInfoWidget.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/475)

Restore book card order by search score (BL-11137)

---

src/components/BlorgLink.tsx
src/components/CheapCard.tsx
src/components/LanguageCard.tsx
src/components/appHosted/AppHostedLanguageGroup.tsx

Also fixes a problem where the preferred language card was not width-restricted like the others on small screens.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/474)

Make click on language work while input focused (BL-11575)

---

src/components/LanguageGroup.tsx
src/components/appHosted/AppHostedLanguageGroup.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/473)

Filter out unused languages at the query level

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/477)

Handle books where level and computedLevel differ (BL-11654)

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/478)

Avoid errors with complex (aka long?) parse book queries (BL-11664)

---

src/components/appHosted/AppHostedLanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/479)

Scroll to top when typing to filter languages (BL-11687)

---

src/components/appHosted/AppHostedUtils.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/484)

Fix app-hosted detection in /#!/app-hosted intermediate stage.

---

src/components/appHosted/AppHostedUtils.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/485)

Fix bug in detecting /#!/app-hosted

---

src/components/BlorgLink.tsx

Not really tested...don't have a good way to do so without deploying to alpha
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/487)

Kludge to get links to work on IOS (BL-11736) 

---

src/components/Footer.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/488)

Add a Donate button to the Bloom Library footer (BL-11804)

---

src/localization/CollectionLabel.tsx
src/model/Collections.tsx
src/model/ContentInterfaces.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/490)

Allow for template collection label l10n

---

src/components/CheapCard.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bloombooks/bloomlibrary2/491)

Prevent double-click requirement on IOS (BL-11736)

---

src/components/LanguageGroup.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/492)

Final fix for double click on IOS (BL-11736)

---

src/components/Admin/StaffMultiChoosers.tsx
src/components/ByLanguageGroups.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/496)

Prevent invalid features from being added via Staff Panel (BL-11868)

---

.gitignore
package.json
public/index.html
src/App.tsx
src/index.css

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/497)

Add Andika and Noto Serif Toto to built-in fonts

---

src/components/CollectionCard.tsx
src/components/banners/StandardBannerLayout.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/498)

Get just the size images we need from Contentful (BL-11991)

---

src/connection/LibraryQueryHooks.ts
src/model/Language.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/500)

Give newly-uploaded languages an assumed usageCount of 1 (BL-12045)

---

README.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/502)

Update README (BL-9515)

---

src/authentication/authentication.ts
src/authentication/firebase/firebase.ts
src/components/Routes.tsx
src/components/User/LoginForEditor.tsx
src/connection/ParseServerConnection.ts
src/editor.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/501)

Tweaks for editor log in (BL-12025)

---

src/components/ReleaseNotes.tsx
src/components/Routes.tsx
src/components/pages/ContentfulMultiPartPage.tsx
src/components/pages/ContentfulPage.tsx
src/components/pages/ThemeForLocation.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/503)

Fix browser tab title for Contentful pages (BL-12087)

---

src/connection/UseContentful.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/504)

Correct/clarify comment about Contentful getEntries limit (BL-11653)

---

README.md
src/components/Grid/GridColumns.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/506)

BL-12551 Enabled grid selection on Leveled Reader Levels

---

.vscode/settings.json
src/components/Breadcrumbs.tsx
src/components/ByLanguageCards.tsx
src/components/ByLanguageGroups.tsx
src/components/ByLevelGroups.tsx
src/components/ByTopicsGroups.tsx
src/components/CollectionCard.tsx
src/components/CollectionLayout.tsx
src/components/CollectionPage.tsx
src/components/CollectionSubsetPage.tsx
src/components/LanguageCard.tsx
src/components/LanguageGroup.tsx
src/model/Collections.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/510)

Add new layout: by-language-cards (BL-12710)

---

src/components/BookDetail/ArtifactHelper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/511)

Generate and simplify the bookOrder URL (BL-12568)

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/512)

Add bookInstanceId: to the array of search facet identifiers

---

src/components/ByLanguageCards.tsx
src/components/CollectionLayout.tsx
src/components/CollectionSubsetPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/513)

BL-12789 Control layout after language cards

---

src/components/BookCard.tsx
src/components/BookCardGroup.tsx
src/components/BookGroup.tsx
src/components/ByLanguageCards.tsx
src/components/ByLanguageGroups.tsx
src/components/ByLevelGroups.tsx
src/components/ByTopicsGroups.tsx
src/components/CheapCard.tsx
src/components/CollectionInfoWidget.tsx
src/components/InfoIconWithTooltip.tsx
src/components/LanguageFeatureList.tsx
src/connection/LibraryQueryHooks.ts
src/model/ContentInterfaces.ts
src/model/DuplicateBookFilter.ts
src/theme.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/514)

BL-12752 Limit display of redundant books in a language

---

src/connection/LibraryQueryHooks.test.ts
src/connection/LibraryQueryHooks.ts
src/connection/LibraryQueryHooksFast.test.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/516)

Simplify inner queries and fix unit tests (BL-12568)

---

src/analytics/CollectionAnalyticsInfo.ts
src/components/BookCard.tsx
src/components/BookCardGroup.tsx
src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/BookDetailHeaderGroup.tsx
src/components/BookDetail/DownloadPreflightDialog.tsx
src/components/BookDetail/DownloadToBloomButton.tsx
src/components/BookDetail/DownloadingShellbookDialog.tsx
src/components/BookDetail/ReadButton.tsx
src/components/BookDetail/ReadOfflineButton.tsx
src/components/BookDetail/ReportButton.tsx
src/components/BookDetail/ReportDialog.tsx
src/components/BookDetail/SharingButtons.tsx
src/components/BookGroup.tsx
src/components/ByLanguageGroups.tsx
src/components/ByLevelGroups.tsx
src/components/ByTopicsGroups.tsx
src/components/ReadBookPage.tsx
src/components/Routes.tsx
src/components/appHosted/AppHostedDownloadButton.tsx

Fixes a bug in which we could have a collection with both of these properties at the same time.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/515)

contextLangIso --> contextLangTag

---

src/components/CollectionSubsetPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/517)

Fix bug I introduced in BL-12789

---

src/components/ByLanguageGroups.tsx
src/model/Book.ts
src/model/DuplicateBookFilter.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/521)

Add title to what we consider when looking for duplicates

---

src/components/BookDetail/DownloadToBloomButton.tsx
src/components/header/Header.tsx
src/components/pages/ThemeForLocation.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/524)

Fix theming for Create-Seeds collection (BL-12836)

---

src/components/ByLanguageGroups.tsx
src/connection/LibraryQueryHooks.ts
src/localization/Code Strings.json
src/model/DuplicateBookFilter.ts
src/model/Language.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/522)

Show "Picture Books" in language card list (BL-12827)

---

src/components/CollectionSubsetPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/526)

Ensure topic subcollection displays levels (BL-12842)

---

src/components/BookDetail/ArtifactHelper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/527)

Introduce minVersion logic for book downloads (BL-12873)

---

src/components/BlorgLink.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/529)

Maintain formats parameter

---

src/components/User/UserMenu.tsx

user menu opens on left if there is no gravatar
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/530)

Bl-12923 fix user menu position if no gravatar

---

src/model/DuplicateBookFilter.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/531)

Prevent duplicate filter from errantly hiding SL books (BL-12871)

---

src/components/Grid/GridControlInternal.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/532)

Draft books are visible only to staff in the grid page (BL-12973)

---

src/components/Grid/GridColumns.tsx
src/components/Grid/GridControlInternal.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/533)

Require logging in for Grid draft and inCirculation columns (BL-12973)

---

src/components/LanguageFeatureList.tsx

"default" 1st title should be L1
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/534)

BL-12947 Show L1 first by default (after any page context lang)

---

src/components/BookDetail/ArtifactHelper.ts
src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/BookExtraPanels.tsx
src/components/BookDetail/DownloadToBloomButton.tsx
src/components/BookDetail/DownloadingShellbookDialog.tsx
src/connection/ParseServerConnection.ts
src/localization/Code Strings.json

Requires a parallel change on Bloom Desktop, not yet implemented; but it should be harmless to merge this independently.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/535)

Book download into a new collection for editing (BL-13035)

---

src/components/BookDetail/BookDetail.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/536)

Allow new download for edit behavior on dev site (BL-13035)

---

src/components/Grid/GridColumns.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/537)

BL-13048 grid view hide notes col for nonstaff

---

src/components/Routes.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/538)

Comment out the unsuccessful fix for urls with hashes (BL-11768)

---

src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/DownloadingShellbookDialog.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/539)

Improve message for edit download, and permit for moderators (BL-13035)

---

src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/BookOwnerControlsBox.tsx
src/components/BookDetail/DeleteButton.tsx
src/components/User/AvatarCircle.tsx
src/components/User/UserMenu.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/540)

BL-13033 reorg book owner controls

---

src/components/BookDetail/BookDetail.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/541)

BL-13033 fix unused import

---

src/components/BookDetail/ArtifactHelper.ts

GIves, e.g.
bloom://localhost/order?orderFile=BloomLibraryBooks/kuytemiar%40gmail.com%2ffd1d1857-80a1-44cc-ba11-e9a8342d45ae%2f&title=Chare%20%C3%88dapad%20Duid%20N%C3%B2m%20Kebek%20Kachakh&minVersion=4.8&forEdit=true&database-id=bWjltsU2iS'
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/542)

BL-13035 id in download URL

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/543)

Make queries more efficient by assuming certain booleans have values

---

src/components/BookDetail/BookOwnerControlsBox.tsx
src/components/BookDetail/DeleteButton.tsx
src/connection/ApiConnection.ts
src/connection/DataSource.ts
src/connection/LibraryQueryHooks.ts
src/connection/LibraryUpdates.ts
src/connection/ParseServerConnection.ts

Ready for review.
Draft because it must go in after
https://github.com/BloomBooks/bloom-azure-functions/pull/81
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/544)

Allow collection editors to delete books (BL-12726)

---

src/components/BookDetail/ArtifactHelper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/546)

Inform Bloom Editor that download-for-edit needs 5.7 (BL-13283)

---

src/components/BookDetail/DownloadingShellbookDialog.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/547)

Try Again on downloadForEdit should do that (BL-13291)

---

src/components/BookDetail/HarvestProgressNotice.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/550)

Fix misleading error message (BL-13499)

---

src/connection/LibraryQueryHooksFast.test.ts
src/localization/Topics And Features.json
src/model/ClosedVocabularies.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/551)

Replace "Spiritual" topic with "Bible" (BL-13538)

---

src/components/Grid/GridColumns.tsx
src/components/Grid/GridExport.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/552)

BL-13567 add lang codes to grid

---

src/components/header/Header.tsx
src/components/pages/ThemeForLocation.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/555)

Add About tab and change Create to Resources (BL-13299)

---

src/components/BookDetail/BookDetail.tsx
src/components/BookDetail/BookExtraPanels.tsx
src/components/BookDetail/BookOwnerControlsBox.tsx
src/components/BookDetail/ControlsBox.tsx
src/components/BookDetail/StaffControlsBox.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/556)

Move staff controls to separate box (BL-13272)

---

src/components/ListOfBookGroups.tsx
src/components/NoSearchResults.tsx
src/localization/Code Strings.json

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/553)

Improve the UI for empty search and Search Deeper (BL-13307)

---

src/components/Breadcrumbs.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/559)

Add italic to emphasis for search strings (BL-13307)

---

src/components/AggregateGrid/AggregateGridPage.tsx
src/components/CountryGrid/CountryGridControlInternal.tsx
src/components/LanguageGrid/LanguageGridColumns.tsx
src/components/LanguageGrid/LanguageGridControlInternal.tsx
src/components/UploaderGrid/UploaderGridControlInternal.tsx

Also preserve login status when jumping to linked pages from grids.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/561)

Handle irregular language tags for grids (BL-13305)

---

src/components/AggregateGrid/AggregateGridInterfaces.ts
src/components/AggregateGrid/AggregateGridPage.tsx
src/components/CountryGrid/CountryGridColumns.tsx
src/components/CountryGrid/CountryGridControlInternal.tsx
src/components/LanguageGrid/LanguageGridControlInternal.tsx
src/components/UploaderGrid/UploaderGridControlInternal.tsx
src/connection/LibraryQueryHooks.ts

A couple of other tweaks, plus commented out code to improve guess of lang1 for each book if we decide we want that information.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/563)

Use all languages for counting books, not just lang1 (BL-13305)

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/565)

Filter out rebrandings for new grids (BL-13305)

---

src/components/AggregateGrid/AggregateGridPage.tsx
src/components/CountryGrid/CountryGridColumns.tsx
src/components/LanguageGrid/LanguageGridColumns.tsx
src/components/UploaderGrid/UploaderGridColumns.tsx

Make filtering more robust for missing data.  Also make uploader emails into links in the Uploaders Grid as well as the Languages Grid.
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/566)

Fix new grid filtering to be case-insensitive everywhere (BL-13505)

---

public/sitemap.xml
src/components/Admin/StaffPanel.tsx
src/components/BookCardGroup.tsx
src/components/BookDetail/ArtifactVisibilityPanel/ArtifactAndChoice.tsx
src/components/BookDetail/BookOwnerControlsBox.tsx
src/components/BookDetail/DownloadToBloomButton.tsx
src/components/BookDetail/DownloadsGroup.tsx
src/components/BookDetail/GetBloomReaderButton.tsx
src/components/BookDetail/GetTemplateButton.tsx
src/components/BookDetail/HarvestProgressNotice.tsx
src/components/BookDetail/TranslateButton.tsx
src/components/ButtonRow.tsx
src/components/Footer.tsx
src/components/Routes.tsx
src/components/SearchBox.tsx
src/components/SearchDeeper.tsx
src/components/banners/StandardBannerLayout.tsx
src/components/header/Header.tsx
src/components/markdown/FeatureMatrix/FeatureGroup.tsx
src/components/markdown/FeatureMatrix/FeatureMatrix.tsx
src/components/markdown/InstallerDownload.tsx
src/components/markdown/Testimonial.tsx
src/components/markdown/WindowsInstallerDownload.tsx
src/components/pages/ContentfulPage.tsx
src/components/pages/ThemeForLocation.tsx
src/theme.tsx

Also fixed Search Deeper functionality and button color
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/558)

Change "create" to "resources" in urls (BL-13299)

---

src/components/ByLanguageCards.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/528)

Show by level after topic + language (BL-12859)

---

src/components/BookDetail/ArtifactHelper.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/567)

Fix BL-13338, make downloads not show spaces as "+"

---

src/components/Grid/GridColumns.tsx
src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/568)

Allow grid to filter on license (BL-13916)

---

src/connection/LibraryQueryHooks.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/569)

Use exact match for license filtering (BL-13916)

---

src/components/Grid/GridColumns.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/570)

Show level in grid even for computed levels (BL-13995)

---

src/components/Grid/GridColumns.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/571)

Allow Reads and Downloads to be sorted in books grid (BL-13994)

---

src/components/Grid/GridColumns.tsx
src/connection/LibraryQueryHooks.ts
src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/572)

Grid: distinguish between read starts and finishes (BL-13994)

---

src/components/Grid/GridColumns.tsx
src/components/Grid/GridExport.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/575)

Sync up grid export with grid (BL-14047)

---

src/components/ReadBookPage.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/576)

Remove extra white space below player iframe and scrollbar (BL-14065)

---

src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/577)

Replace newlines in titles for better display (BL-13210)

---

src/components/Grid/GridControlInternal.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/578)

Reset to first page of grid results when filter changes (BL-14029)

---

src/components/statistics/BookStatsReport.tsx
src/components/statistics/StatsInterfaces.ts
src/connection/LibraryQueryHooks.ts
src/model/Language.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/579)

BL-14205 Add language tag to book stats

---

src/export/exportData.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/580)

Fix csv export when there is an empty value (BL-14280)

---

src/connection/ApiConnection.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/582)

Fix appending dev parameter for api call (BL-14033)

---

src/analytics/Analytics.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/583)

Whitelist limited number of analytic events (BL-14518)

---

src/components/markdown/FeatureMatrix/Feature.tsx
src/components/markdown/FeatureMatrix/FeatureCodeSplit.tsx
src/components/markdown/FeatureMatrix/FeatureMatrix.tsx
src/components/markdown/FeatureMatrix/FeatureMatrixCodeSplit.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/584)

Enhance FeatureMatrix code for pro subscription level (BL-14577)

---

src/analytics/Analytics.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/585)

Whitelist drag-game events (BL-14796)

---

src/components/AlphaTilesButton.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/587)

Make AlphaTiles links work better in Bloom Reader (BL-14983)

---

package.json
src/components/LanguageGroup.tsx
yarn.lock

I will update the ethnolib version in this PR once https://github.com/sillsdev/EthnoLib/pull/109 is merged
- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/588)

BL-14706 use Language Chooser for fuzzy searching languages

---

src/connection/sorting.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/591)

Fix crash during sorting due to wierd language tag (BL-15191)

---

src/model/Book.ts

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/592)

Allow hyphens in font names for error reports (BL-15273)

---

src/components/BookDetail/StaffControlsBox.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/596)

Don't make updating book information reload book detail page (BL-15324)

---

src/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/BloomBooks/BloomLibrary2/597)

Workaround Google Translate vs. React issue (BL-15339)
